img= new Array();
img[0]=new Image();
img[1]=new Image();
img[2]=new Image();
img[3]=new Image();
img[4]=new Image();
img[5]=new Image();
img[6]=new Image();
img[7]=new Image();
img[8]=new Image();
img[9]=new Image();
img[10]=new Image();
img[11]=new Image();
img[12]=new Image();
img[13]=new Image();

img[0].src="images/but.png"
img[1].src="images/hbut.png"
img[2].src="images/car1.png"
img[3].src="images/car2.png"
img[4].src="images/car3.png"
img[5].src="images/car4.png"
img[6].src="images/car5.png"
img[7].src="images/car6.png"
img[8].src="images/car7.png"
img[9].src="images/car8.png"
img[10].src="images/hbut71.png"
img[11].src="images/hbut81.png"
img[12].src="images/hbut91.png"
img[13].src="images/hbut11.png"
