img= new Array();
img[0]=new Image();
img[1]=new Image();
img[2]=new Image();
img[3]=new Image();
img[4]=new Image();
img[5]=new Image();
img[6]=new Image();
img[7]=new Image();
img[8]=new Image();
img[9]=new Image();
img[10]=new Image();
img[11]=new Image();
img[12]=new Image();
img[13]=new Image();
img[14]=new Image();
img[15]=new Image();
img[16]=new Image();
img[17]=new Image();
img[18]=new Image();
img[19]=new Image();
img[20]=new Image();
img[21]=new Image();
img[22]=new Image();
img[23]=new Image();
img[24]=new Image();
img[25]=new Image();
img[26]=new Image();
img[27]=new Image();
img[28]=new Image();
img[29]=new Image();

img[0].src="images/but.png"
img[1].src="images/hbut.png"
img[2].src="images/car1.png"
img[3].src="images/car2.png"
img[4].src="images/car3.png"
img[5].src="images/car4.png"
img[6].src="images/car5.png"
img[7].src="images/car6.png"
img[8].src="images/car7.png"
img[9].src="images/car8.png"
img[10].src="images/but71.png"
img[11].src="images/but81.png"
img[12].src="images/but91.png"
img[13].src="images/but11.png"
img[14].src="images/hbut71.png"
img[15].src="images/hbut81.png"
img[16].src="images/hbut91.png"
img[17].src="images/hbut11.png"
img[18].src="images/hltc1.png"
img[19].src="images/hltc2.png"
img[20].src="images/hltc3.png"
img[21].src="images/hltc4.png"
img[22].src="images/hltc5.png"
img[23].src="images/hltc6.png"
img[24].src="images/hltc7.png"
img[25].src="images/hrtc1.png"
img[26].src="images/hrtc2.png"
img[27].src="images/hrtc3.png"
img[28].src="images/hrtc4.png"
img[29].src="images/hrtc5.png"